[[language]]
name = "go"

# renamed the default gopls
language-servers = [ "go-lsp", "golangci-lint" ]
formatter = { command = "${HOME}/go/bin/goimports" }

[language-server.go-lsp]
command = "${HOME}/go/bin/gopls"


[language-server.go-lsp.config]
local = "goimports"
semanticTokens = true
staticcheck = true
verboseOutput = true
usePlaceholders = true
completeUnimported = true


[language-server.go-lsp.config.analyses]
fieldalignment = true
nilness = true
unusedparams = true
unusedwrite = true
useany = true


[language-server.go-lsp.config.hints]
assignVariableTypes = true
compositeLiteralFields = true
compositeLiteralTypes = true
constantValues = true
functionTypeParameters = true
parameterNames = true
rangeVariableTypes = true

[language-server.golangci-lint]
command = "${HOME}/go/bin/golangci-lint"
args =  ["run", "--output.json.path=stdout", "--show-stats=false", "--issues-exit-code=1"]

[[grammar]]
name = "go"
source = { git = "https://github.com/tree-sitter/tree-sitter-go", rev = "64457ea6b73ef5422ed1687178d4545c3e91334a" }
